# Generated by Django 5.1.5 on 2025-02-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
