# Generated by Django 5.1.5 on 2025-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0002_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', editable=False),
        ),
    ]
