# Generated by Django 5.1.5 on 2025-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0005_website_latitude_website_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='website',
            name='longitude',
        ),
        migrations.AddField(
            model_name='website',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
