# Generated by Django 5.1.6 on 2025-03-10 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0006_remove_website_latitude_remove_website_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
