# Generated by Django 5.1.5 on 2025-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0007_remove_website_location_website_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
