# Generated by Django 5.1.5 on 2025-03-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0007_website_date'),
        ('qrgenerator', '0008_website_address'),
    ]

    operations = [
    ]
