# Generated by Django 5.1.6 on 2025-02-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.TextField(unique=True, verbose_name='Card Name')),
                ('image', models.TextField(default='Missing Image', verbose_name='Image URL')),
                ('card_desc', models.TextField(blank=True, verbose_name='Card Description')),
                ('rarity', models.IntegerField(verbose_name='Rarity')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='OwnedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'OwnedCard',
                'verbose_name_plural': 'OwnedCards',
            },
        ),
    ]
