# Generated by Django 5.1.5 on 2025-02-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata', verbose_name='User Data'),
        ),
        migrations.AddField(
            model_name='packcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='Card'),
        ),
        migrations.AddField(
            model_name='packcards',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.pack', verbose_name='Pack'),
        ),
        migrations.AddField(
            model_name='pack',
            name='cards',
            field=models.ManyToManyField(through='cards.PackCards', to='cards.card', verbose_name='Cards'),
        ),
        migrations.AddConstraint(
            model_name='ownedcard',
            constraint=models.UniqueConstraint(fields=('card', 'owner'), name='Unique Owned Card'),
        ),
        migrations.AddConstraint(
            model_name='packcards',
            constraint=models.UniqueConstraint(fields=('card', 'pack'), name='Unique Pack Card'),
        ),
    ]
