# Generated by Django 5.1.6 on 2025-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
        ('user', '0003_ownedbadge_unique_owned_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedcard',
            old_name='user_data',
            new_name='owner',
        ),
        migrations.AddConstraint(
            model_name='ownedcard',
            constraint=models.UniqueConstraint(fields=('card', 'owner'), name='Unique Owned Card'),
        ),
    ]
