# Generated by Django 5.1.6 on 2025-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_image_alter_pack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='src/apps/cards/images/Missing_Texture.png', upload_to='src/apps/cards/images/', verbose_name='Image File Path'),
        ),
    ]
