# Generated by Django 5.1.6 on 2025-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='./images/card_images/Missing_Texture.png', upload_to='./images/card_images/', verbose_name='Image File Path'),
        ),
    ]
