# Generated by Django 5.1.6 on 2025-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_desc',
            field=models.TextField(null=True, verbose_name='Card Description'),
        ),
    ]
