# Generated by Django 5.1.6 on 2025-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_card_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Card Description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='.\\images\\card_images\\Missing_Texture.png', upload_to='.\\images\\card_images', verbose_name='Image File Path'),
        ),
    ]
