# Generated by Django 5.1.6 on 2025-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_card_desc_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='.\\static\\images\\card_images\\Missing_Texture.png', upload_to='.\\static\\images\\card_images', verbose_name='Image File Path'),
        ),
    ]
