# Generated by Django 5.1.5 on 2025-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.TextField(default='./photos/cards/missing.png', verbose_name='Image Url'),
        ),
    ]
