# Generated by Django 5.1.6 on 2025-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.TextField(default='/images/card_images/Missing_Texture.png', verbose_name='Image Url'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.TextField(default='/images/card_images/Missing_Texture.png', verbose_name='Pack Image'),
        ),
    ]
