# Generated by Django 5.1.6 on 2025-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_card_image_alter_pack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_frame',
            field=models.IntegerField(default=0, verbose_name='Card Frame'),
        ),
    ]
