# Generated by Django 5.1.5 on 2025-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_card_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.TextField(default='images/card_images/Missing_Texture.png', verbose_name='Image Url'),
        ),
    ]
