# Generated by Django 5.1.6 on 2025-02-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata', verbose_name='User Data'),
        ),
    ]
