# Generated by Django 5.1.5 on 2025-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='badges',
            field=models.ManyToManyField(blank=True, to='user.badge', verbose_name='Badges'),
        ),
    ]
