# Generated by Django 5.1.6 on 2025-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ownedbadge',
            constraint=models.UniqueConstraint(fields=('badge', 'owner'), name='Unique Owned Badge'),
        ),
    ]
